services:
  jenkins:
    image: my-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: my-jenkins
    network_mode: bridge