services:

  jenkins:
    build: .
    image: my-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: my-jenkins
    networks:
      - dind-network
  
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    container_name: my-sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    networks:
      - dind-network
  
networks:
  dind-network: {}