pipeline {
    agent any
    
    tools {
        nodejs 'node18'
    }

    environment {
        SONAR_SCANNER_HOME = tool 'sonar-scanner'
        SONAR_PROJECT_KEY = 'nodeapp'
        DOCKER_IMAGE = "conandor/nodeapp:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Github') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/kimhan9/jenkins-container.git'
            }
        }

        stage('Unit Test'){
			steps {
                dir('nodeapp') {
				    sh 'npm test'
				    sh 'npm install'
                }
			}
		}

		stage('SonarQube Analysis'){
			steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('sonar-server') {
    					sh """
						${SONAR_SCANNER_HOME}/bin/sonar-scanner \
						-Dsonar.projectKey=${SONAR_PROJECT_KEY} \
						-Dsonar.sources=. \
						-Dsonar.host.url=http://my-sonarqube:9000 \
						-Dsonar.login=${SONAR_TOKEN}
						"""
                    }
                }
			}
		}
		
        stage('Build Image') {
            steps {
                dir('nodeapp') {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }
        
        stage('Trivy Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL --no-progress ${DOCKER_IMAGE}"
            }
        }
        
        stage('Docker Push'){
            steps{
                script {
                    withDockerRegistry(credentialsId: 'dockerhub', toolName: 'docker') {
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }
        
    }
}