pipeline {
    agent any
    
    tools {
        nodejs 'node18'
    }

    stages {
        stage('Github') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/kimhan9/jenkins-container.git'
            }
        }
        stage('Unit Test'){
			steps {
				sh 'npm test'
				sh 'npm install'		
			}
		}
    }
}
