pipeline {
    agent any
    
    tools {
        nodejs 'node18'
    }

    environment {
        SONAR_SCANNER_HOME = tool 'sonar-scanner'
        SONAR_PROJECT_KEY = 'nodeapp'
        DOCKER_HUB_REPO = 'conandor/nodeapp'
    }

    stages {
        stage('Github') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/kimhan9/jenkins-container.git'
            }
        }

        stage('Unit Test'){
			steps {
                dir('nodeapp') {
				    sh 'npm test'
				    sh 'npm install'
                }
			}
		}

        '''
		stage('SonarQube Analysis'){
			steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('sonar-server') {
    					sh """
						${SONAR_SCANNER_HOME}/bin/sonar-scanner \
						-Dsonar.projectKey=${SONAR_PROJECT_KEY} \
						-Dsonar.sources=. \
						-Dsonar.host.url=http://my-sonarqube:9000 \
						-Dsonar.login=${SONAR_TOKEN}
						"""
                    }
                }
			}
		}
        '''

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_HUB_REPO}:${env.BUILD_ID}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        docker.push()
                        docker.push('latest')
                    }
                }
            }
        }
        
    }
}
